### PR TITLE
fix encoding of non-ascii strings

### LINKED ISSUE #360: MessageWritter gone wrong will using special character likes é,à,â,ô...
**Description**
While i'll try to serialize my object using new MessageWritter().writeMessage(myRequest), myRequest containing an object with a key name:string of value 'béta' the serialization modify my string to 'bét', it remove one character per special character . 
example :
'béta' ==> 'bét'
'bééta' ==> 'bé'
'béééta' ==>'b'

- Version:2.0.2
- Platform: macOs

**Steps To Reproduce**

call the function MessageWriter().writeMessage({name:'béta'}) store it in a const
then use MessageReader().readMessage(myConst) you'll have a string containing 'bét'

here is a sample to reproduce the issue :

    const writer = new MessageWriter(parse("string name"));
    const reader = new MessageReader(parse("string name"));
    const test = writer.writeMessage({ name: "béta" });
    console.log("=== result === ", reader.readMessage(test));

this sample will print : Record {name: 'bét'} 

**Expected Behavior**

### PR DESCRIPTION
**Pull request by jtbandes**
### Public-Facing Changes

Fixed a bug where non-ASCII strings would be truncated when `MessageWriter` encoded them as UTF-8.

### Description

Fixes #360

`str.length` is the length of the string in UTF-16. However, we use TextEncoder to encode strings as UTF-8. We could compute the length using TextEncoder itself, but this proves to be much slower than a manual calculation: https://jsbench.me/nzlrkwmeiq/1

### CODE REVIEW

**Review by defunctzombie — APPROVED** [review]

File: src/stringLengthUtf8.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
+/**
+ * Returns the number of bytes that would be used when encoding the string as UTF-8, effectively the
+ * same as `new TextEncoder().encode(str).length` but faster.
```
Comment (snosenzo) [inline src/stringLengthUtf8.ts:3]: worth explaining why it's faster or what the tradeoff for speed is?

**Review by snosenzo — APPROVED** [review]

File: src/stringLengthUtf8.ts (hunk 1 above)
Comment (jtbandes) [reply src/stringLengthUtf8.ts:3]: I'll add a link to the jsbench
```suggestion
 * same as `new TextEncoder().encode(str).length` but faster.
 * https://jsbench.me/nzlrkwmeiq/1
```
